### ISSUE TITLE
points selection for the bird-view transformation

### ISSUE THREAD

**Issue by dawnlh** [lapankrz/Lane-Detecting-Assistant#1]
Hi~ @lapankrz  thanks for the wonderful work,
In `arbitrarily_selected_points()` and `reference_points()` functions, you directly give 4 pairs of coordinates for the calculation of transformation matrix, but I cannot understand how the points are selected. Did you assume that all the images share the same transformation matrix? And can you give a detailed illustration about the points you selected.

**Comment by lapankrz** [comment]
The points were arbitrarily set based on the photos specifically chosen for the project. Their location was loosely based on the edges of the lane that the camera is in, adjusted with some trial and error to get the desired result, which was the bird's eye view of the road. This part of the project could obviously be improved, being replaced with some sort of dynamic point selection based on the detected lines on the road.

**Comment by dawnlh** [comment]
Got it, thanks for your timely response!
